// This file is auto-generated by import_catalog.js
export interface Product {
  id: string
  name: string
  code: string
  category: string
  tags: string[]
  badge?: string
  image: string
  large?: boolean
}

export const catalogProducts: Product[] = [
  {
    "id": "armored-1",
    "name": "باب مصفح فاخر HM-AR-01",
    "code": "HM-AR-01",
    "category": "مصفحة",
    "tags": [
      "مصفح تركي",
      "عازل للصوت",
      "مقاوم للسرقة"
    ],
    "image": "./images/catalog/armored/armored-1.jpeg",
    "large": true
  },
  {
    "id": "armored-2",
    "name": "باب مصفح فاخر HM-AR-02",
    "code": "HM-AR-02",
    "category": "مصفحة",
    "tags": [
      "سمك 10سم",
      "مقاوم للسرقة",
      "قفل متعدد النقاط"
    ],
    "image": "./images/catalog/armored/armored-2.jpeg",
    "large": false
  },
  {
    "id": "armored-3",
    "name": "باب مصفح فاخر HM-AR-03",
    "code": "HM-AR-03",
    "category": "مصفحة",
    "tags": [
      "سمك 10سم",
      "عازل للصوت",
      "مصفح تركي"
    ],
    "image": "./images/catalog/armored/armored-3.jpeg",
    "large": false
  },
  {
    "id": "armored-4",
    "name": "باب مصفح فاخر HM-AR-04",
    "code": "HM-AR-04",
    "category": "مصفحة",
    "tags": [
      "مصفح تركي",
      "عازل للصوت",
      "مقاوم للسرقة"
    ],
    "badge": "الأكثر مبيعاً",
    "image": "./images/catalog/armored/armored-4.jpeg",
    "large": false
  },
  {
    "id": "armored-5",
    "name": "باب مصفح فاخر HM-AR-05",
    "code": "HM-AR-05",
    "category": "مصفحة",
    "tags": [
      "سمك 10سم",
      "مقاوم للسرقة",
      "قفل متعدد النقاط"
    ],
    "image": "./images/catalog/armored/armored-5.jpeg",
    "large": false
  },
  {
    "id": "armored-6",
    "name": "باب مصفح فاخر HM-AR-06",
    "code": "HM-AR-06",
    "category": "مصفحة",
    "tags": [
      "عازل للصوت",
      "مقاوم للسرقة",
      "مصفح تركي"
    ],
    "image": "./images/catalog/armored/armored-6.jpeg",
    "large": false
  },
  {
    "id": "armored-7",
    "name": "باب مصفح فاخر HM-AR-07",
    "code": "HM-AR-07",
    "category": "مصفحة",
    "tags": [
      "مصفح تركي",
      "عازل للصوت",
      "سمك 10سم"
    ],
    "image": "./images/catalog/armored/armored-7.jpeg",
    "large": false
  },
  {
    "id": "armored-8",
    "name": "باب مصفح فاخر HM-AR-08",
    "code": "HM-AR-08",
    "category": "مصفحة",
    "tags": [
      "قفل متعدد النقاط",
      "مصفح تركي",
      "عازل للصوت"
    ],
    "image": "./images/catalog/armored/armored-8.jpeg",
    "large": false
  },
  {
    "id": "armored-9",
    "name": "باب مصفح فاخر HM-AR-09",
    "code": "HM-AR-09",
    "category": "مصفحة",
    "tags": [
      "سمك 10سم",
      "مصفح تركي",
      "عازل للصوت"
    ],
    "badge": "جديد",
    "image": "./images/catalog/armored/armored-9.jpeg",
    "large": false
  },
  {
    "id": "armored-10",
    "name": "باب مصفح فاخر HM-AR-10",
    "code": "HM-AR-10",
    "category": "مصفحة",
    "tags": [
      "قفل متعدد النقاط",
      "مصفح تركي",
      "سمك 10سم"
    ],
    "image": "./images/catalog/armored/armored-10.jpeg",
    "large": false
  },
  {
    "id": "sada-1",
    "name": "باب غرف سادة مودرن HM-SD-01",
    "code": "HM-SD-01",
    "category": "سادة",
    "tags": [
      "سهل التنظيف",
      "مقاوم للخدش",
      "حشو فونت كندي"
    ],
    "badge": "الأكثر مبيعاً",
    "image": "./images/catalog/sada/sada-1.jpeg",
    "large": false
  },
  {
    "id": "sada-2",
    "name": "باب غرف سادة مودرن HM-SD-02",
    "code": "HM-SD-02",
    "category": "سادة",
    "tags": [
      "HPL سادة",
      "حشو فونت كندي",
      "مقاوم للخدش"
    ],
    "image": "./images/catalog/sada/sada-2.jpeg",
    "large": false
  },
  {
    "id": "sada-3",
    "name": "باب غرف سادة مودرن HM-SD-03",
    "code": "HM-SD-03",
    "category": "سادة",
    "tags": [
      "مقاوم للخدش",
      "حشو فونت كندي",
      "سهل التنظيف"
    ],
    "image": "./images/catalog/sada/sada-3.jpeg",
    "large": false
  },
  {
    "id": "sada-4",
    "name": "باب غرف سادة مودرن HM-SD-04",
    "code": "HM-SD-04",
    "category": "سادة",
    "tags": [
      "حشو فونت كندي",
      "عزل حراري",
      "HPL سادة"
    ],
    "badge": "راقي",
    "image": "./images/catalog/sada/sada-4.jpeg",
    "large": false
  },
  {
    "id": "sada-5",
    "name": "باب غرف سادة مودرن HM-SD-05",
    "code": "HM-SD-05",
    "category": "سادة",
    "tags": [
      "عزل حراري",
      "HPL سادة",
      "مقاوم للخدش"
    ],
    "image": "./images/catalog/sada/sada-5.jpeg",
    "large": false
  },
  {
    "id": "sada-6",
    "name": "باب غرف سادة مودرن HM-SD-06",
    "code": "HM-SD-06",
    "category": "سادة",
    "tags": [
      "عزل حراري",
      "HPL سادة",
      "حشو فونت كندي"
    ],
    "image": "./images/catalog/sada/sada-6.jpeg",
    "large": false
  },
  {
    "id": "sada-7",
    "name": "باب غرف سادة مودرن HM-SD-07",
    "code": "HM-SD-07",
    "category": "سادة",
    "tags": [
      "مقاوم للخدش",
      "عزل حراري",
      "حشو فونت كندي"
    ],
    "image": "./images/catalog/sada/sada-7.jpeg",
    "large": false
  },
  {
    "id": "sada-8",
    "name": "باب غرف سادة مودرن HM-SD-08",
    "code": "HM-SD-08",
    "category": "سادة",
    "tags": [
      "HPL سادة",
      "حشو فونت كندي",
      "مقاوم للخدش"
    ],
    "image": "./images/catalog/sada/sada-8.jpeg",
    "large": false
  },
  {
    "id": "two-colors-1",
    "name": "باب غرف لونين عصري HM-TC-01",
    "code": "HM-TC-01",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "مقاوم للرطوبة",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-1.jpeg",
    "large": false
  },
  {
    "id": "two-colors-2",
    "name": "باب غرف لونين عصري HM-TC-02",
    "code": "HM-TC-02",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "تصميم مودرن",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-2.jpeg",
    "large": false
  },
  {
    "id": "two-colors-3",
    "name": "باب غرف لونين عصري HM-TC-03",
    "code": "HM-TC-03",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "دهان استر فاخر",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-3.jpeg",
    "large": false
  },
  {
    "id": "two-colors-4",
    "name": "باب غرف لونين عصري HM-TC-04",
    "code": "HM-TC-04",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "إطار مزدوج",
      "مقاوم للرطوبة"
    ],
    "image": "./images/catalog/two-colors/two-colors-4.jpeg",
    "large": false
  },
  {
    "id": "two-colors-5",
    "name": "باب غرف لونين عصري HM-TC-05",
    "code": "HM-TC-05",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "تصميم مودرن",
      "تناسق ألوان"
    ],
    "image": "./images/catalog/two-colors/two-colors-5.jpeg",
    "large": false
  },
  {
    "id": "two-colors-6",
    "name": "باب غرف لونين عصري HM-TC-06",
    "code": "HM-TC-06",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "تصميم مودرن",
      "تناسق ألوان"
    ],
    "image": "./images/catalog/two-colors/two-colors-6.jpeg",
    "large": false
  },
  {
    "id": "two-colors-7",
    "name": "باب غرف لونين عصري HM-TC-07",
    "code": "HM-TC-07",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "تناسق ألوان",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-7.jpeg",
    "large": false
  },
  {
    "id": "two-colors-8",
    "name": "باب غرف لونين عصري HM-TC-08",
    "code": "HM-TC-08",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "تصميم مودرن",
      "دهان استر فاخر"
    ],
    "image": "./images/catalog/two-colors/two-colors-8.jpeg",
    "large": false
  },
  {
    "id": "two-colors-9",
    "name": "باب غرف لونين عصري HM-TC-09",
    "code": "HM-TC-09",
    "category": "لونين",
    "tags": [
      "تصميم مودرن",
      "مقاوم للرطوبة",
      "دهان استر فاخر"
    ],
    "badge": "جديد",
    "image": "./images/catalog/two-colors/two-colors-9.jpeg",
    "large": false
  },
  {
    "id": "two-colors-10",
    "name": "باب غرف لونين عصري HM-TC-10",
    "code": "HM-TC-10",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "مقاوم للرطوبة",
      "تناسق ألوان"
    ],
    "image": "./images/catalog/two-colors/two-colors-10.jpeg",
    "large": false
  },
  {
    "id": "two-colors-11",
    "name": "باب غرف لونين عصري HM-TC-11",
    "code": "HM-TC-11",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "مقاوم للرطوبة",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-11.jpeg",
    "large": false
  },
  {
    "id": "two-colors-12",
    "name": "باب غرف لونين عصري HM-TC-12",
    "code": "HM-TC-12",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "دهان استر فاخر",
      "تصميم مودرن"
    ],
    "badge": "راقي",
    "image": "./images/catalog/two-colors/two-colors-12.jpeg",
    "large": false
  },
  {
    "id": "two-colors-13",
    "name": "باب غرف لونين عصري HM-TC-13",
    "code": "HM-TC-13",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "دهان استر فاخر",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-13.jpeg",
    "large": false
  },
  {
    "id": "two-colors-14",
    "name": "باب غرف لونين عصري HM-TC-14",
    "code": "HM-TC-14",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "تصميم مودرن",
      "مقاوم للرطوبة"
    ],
    "image": "./images/catalog/two-colors/two-colors-14.jpeg",
    "large": false
  },
  {
    "id": "two-colors-15",
    "name": "باب غرف لونين عصري HM-TC-15",
    "code": "HM-TC-15",
    "category": "لونين",
    "tags": [
      "تصميم مودرن",
      "تناسق ألوان",
      "إطار مزدوج"
    ],
    "badge": "جديد",
    "image": "./images/catalog/two-colors/two-colors-15.jpeg",
    "large": false
  },
  {
    "id": "two-colors-16",
    "name": "باب غرف لونين عصري HM-TC-16",
    "code": "HM-TC-16",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "إطار مزدوج",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-16.jpeg",
    "large": false
  },
  {
    "id": "two-colors-17",
    "name": "باب غرف لونين عصري HM-TC-17",
    "code": "HM-TC-17",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "تصميم مودرن",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-17.jpeg",
    "large": false
  },
  {
    "id": "two-colors-18",
    "name": "باب غرف لونين عصري HM-TC-18",
    "code": "HM-TC-18",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "إطار مزدوج",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-18.jpeg",
    "large": false
  },
  {
    "id": "two-colors-19",
    "name": "باب غرف لونين عصري HM-TC-19",
    "code": "HM-TC-19",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "دهان استر فاخر",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-19.jpeg",
    "large": false
  },
  {
    "id": "two-colors-20",
    "name": "باب غرف لونين عصري HM-TC-20",
    "code": "HM-TC-20",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "تناسق ألوان",
      "دهان استر فاخر"
    ],
    "image": "./images/catalog/two-colors/two-colors-20.jpeg",
    "large": false
  },
  {
    "id": "two-colors-21",
    "name": "باب غرف لونين عصري HM-TC-21",
    "code": "HM-TC-21",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "تناسق ألوان",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-21.jpeg",
    "large": false
  },
  {
    "id": "two-colors-22",
    "name": "باب غرف لونين عصري HM-TC-22",
    "code": "HM-TC-22",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "تصميم مودرن",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-22.jpeg",
    "large": false
  },
  {
    "id": "two-colors-23",
    "name": "باب غرف لونين عصري HM-TC-23",
    "code": "HM-TC-23",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "مقاوم للرطوبة",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-23.jpeg",
    "large": false
  },
  {
    "id": "two-colors-24",
    "name": "باب غرف لونين عصري HM-TC-24",
    "code": "HM-TC-24",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "مقاوم للرطوبة",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-24.jpeg",
    "large": false
  },
  {
    "id": "two-colors-25",
    "name": "باب غرف لونين عصري HM-TC-25",
    "code": "HM-TC-25",
    "category": "لونين",
    "tags": [
      "إطار مزدوج",
      "مقاوم للرطوبة",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-25.jpeg",
    "large": false
  },
  {
    "id": "two-colors-26",
    "name": "باب غرف لونين عصري HM-TC-26",
    "code": "HM-TC-26",
    "category": "لونين",
    "tags": [
      "إطار مزدوج",
      "تصميم مودرن",
      "تناسق ألوان"
    ],
    "image": "./images/catalog/two-colors/two-colors-26.jpeg",
    "large": false
  },
  {
    "id": "two-colors-27",
    "name": "باب غرف لونين عصري HM-TC-27",
    "code": "HM-TC-27",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "تناسق ألوان",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-27.jpeg",
    "large": false
  },
  {
    "id": "two-colors-28",
    "name": "باب غرف لونين عصري HM-TC-28",
    "code": "HM-TC-28",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "تناسق ألوان",
      "تصميم مودرن"
    ],
    "badge": "جديد",
    "image": "./images/catalog/two-colors/two-colors-28.jpeg",
    "large": false
  },
  {
    "id": "two-colors-29",
    "name": "باب غرف لونين عصري HM-TC-29",
    "code": "HM-TC-29",
    "category": "لونين",
    "tags": [
      "تصميم مودرن",
      "مقاوم للرطوبة",
      "دهان استر فاخر"
    ],
    "image": "./images/catalog/two-colors/two-colors-29.jpeg",
    "large": false
  },
  {
    "id": "two-colors-30",
    "name": "باب غرف لونين عصري HM-TC-30",
    "code": "HM-TC-30",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "تصميم مودرن",
      "مقاوم للرطوبة"
    ],
    "image": "./images/catalog/two-colors/two-colors-30.jpeg",
    "large": false
  },
  {
    "id": "two-colors-31",
    "name": "باب غرف لونين عصري HM-TC-31",
    "code": "HM-TC-31",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "تصميم مودرن",
      "مقاوم للرطوبة"
    ],
    "image": "./images/catalog/two-colors/two-colors-31.jpeg",
    "large": false
  },
  {
    "id": "two-colors-32",
    "name": "باب غرف لونين عصري HM-TC-32",
    "code": "HM-TC-32",
    "category": "لونين",
    "tags": [
      "إطار مزدوج",
      "دهان استر فاخر",
      "مقاوم للرطوبة"
    ],
    "image": "./images/catalog/two-colors/two-colors-32.jpeg",
    "large": false
  },
  {
    "id": "two-colors-33",
    "name": "باب غرف لونين عصري HM-TC-33",
    "code": "HM-TC-33",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "إطار مزدوج",
      "تناسق ألوان"
    ],
    "image": "./images/catalog/two-colors/two-colors-33.jpeg",
    "large": false
  },
  {
    "id": "two-colors-34",
    "name": "باب غرف لونين عصري HM-TC-34",
    "code": "HM-TC-34",
    "category": "لونين",
    "tags": [
      "إطار مزدوج",
      "دهان استر فاخر",
      "مقاوم للرطوبة"
    ],
    "image": "./images/catalog/two-colors/two-colors-34.jpeg",
    "large": false
  },
  {
    "id": "two-colors-35",
    "name": "باب غرف لونين عصري HM-TC-35",
    "code": "HM-TC-35",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "تصميم مودرن",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-35.jpeg",
    "large": false
  },
  {
    "id": "two-colors-36",
    "name": "باب غرف لونين عصري HM-TC-36",
    "code": "HM-TC-36",
    "category": "لونين",
    "tags": [
      "إطار مزدوج",
      "دهان استر فاخر",
      "مقاوم للرطوبة"
    ],
    "image": "./images/catalog/two-colors/two-colors-36.jpeg",
    "large": false
  },
  {
    "id": "two-colors-37",
    "name": "باب غرف لونين عصري HM-TC-37",
    "code": "HM-TC-37",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "تصميم مودرن",
      "مقاوم للرطوبة"
    ],
    "image": "./images/catalog/two-colors/two-colors-37.jpeg",
    "large": false
  },
  {
    "id": "two-colors-38",
    "name": "باب غرف لونين عصري HM-TC-38",
    "code": "HM-TC-38",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "تناسق ألوان",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-38.jpeg",
    "large": false
  },
  {
    "id": "two-colors-39",
    "name": "باب غرف لونين عصري HM-TC-39",
    "code": "HM-TC-39",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "مقاوم للرطوبة",
      "دهان استر فاخر"
    ],
    "image": "./images/catalog/two-colors/two-colors-39.jpeg",
    "large": false
  },
  {
    "id": "two-colors-40",
    "name": "باب غرف لونين عصري HM-TC-40",
    "code": "HM-TC-40",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "دهان استر فاخر",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-40.jpeg",
    "large": false
  },
  {
    "id": "two-colors-41",
    "name": "باب غرف لونين عصري HM-TC-41",
    "code": "HM-TC-41",
    "category": "لونين",
    "tags": [
      "إطار مزدوج",
      "تناسق ألوان",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-41.jpeg",
    "large": false
  },
  {
    "id": "two-colors-42",
    "name": "باب غرف لونين عصري HM-TC-42",
    "code": "HM-TC-42",
    "category": "لونين",
    "tags": [
      "تصميم مودرن",
      "مقاوم للرطوبة",
      "دهان استر فاخر"
    ],
    "image": "./images/catalog/two-colors/two-colors-42.jpeg",
    "large": false
  },
  {
    "id": "two-colors-43",
    "name": "باب غرف لونين عصري HM-TC-43",
    "code": "HM-TC-43",
    "category": "لونين",
    "tags": [
      "مقاوم للرطوبة",
      "تصميم مودرن",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-43.jpeg",
    "large": false
  },
  {
    "id": "two-colors-44",
    "name": "باب غرف لونين عصري HM-TC-44",
    "code": "HM-TC-44",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "إطار مزدوج",
      "دهان استر فاخر"
    ],
    "image": "./images/catalog/two-colors/two-colors-44.jpeg",
    "large": false
  },
  {
    "id": "two-colors-45",
    "name": "باب غرف لونين عصري HM-TC-45",
    "code": "HM-TC-45",
    "category": "لونين",
    "tags": [
      "إطار مزدوج",
      "تناسق ألوان",
      "دهان استر فاخر"
    ],
    "image": "./images/catalog/two-colors/two-colors-45.jpeg",
    "large": false
  },
  {
    "id": "two-colors-46",
    "name": "باب غرف لونين عصري HM-TC-46",
    "code": "HM-TC-46",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "دهان استر فاخر",
      "تصميم مودرن"
    ],
    "badge": "طلب خاص",
    "image": "./images/catalog/two-colors/two-colors-46.jpeg",
    "large": false
  },
  {
    "id": "two-colors-47",
    "name": "باب غرف لونين عصري HM-TC-47",
    "code": "HM-TC-47",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "إطار مزدوج",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-47.jpeg",
    "large": false
  },
  {
    "id": "two-colors-48",
    "name": "باب غرف لونين عصري HM-TC-48",
    "code": "HM-TC-48",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "إطار مزدوج",
      "تناسق ألوان"
    ],
    "image": "./images/catalog/two-colors/two-colors-48.jpeg",
    "large": false
  },
  {
    "id": "two-colors-49",
    "name": "باب غرف لونين عصري HM-TC-49",
    "code": "HM-TC-49",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "تصميم مودرن",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-49.jpeg",
    "large": false
  },
  {
    "id": "two-colors-50",
    "name": "باب غرف لونين عصري HM-TC-50",
    "code": "HM-TC-50",
    "category": "لونين",
    "tags": [
      "دهان استر فاخر",
      "مقاوم للرطوبة",
      "تصميم مودرن"
    ],
    "image": "./images/catalog/two-colors/two-colors-50.jpeg",
    "large": false
  },
  {
    "id": "two-colors-51",
    "name": "باب غرف لونين عصري HM-TC-51",
    "code": "HM-TC-51",
    "category": "لونين",
    "tags": [
      "تناسق ألوان",
      "دهان استر فاخر",
      "إطار مزدوج"
    ],
    "image": "./images/catalog/two-colors/two-colors-51.jpeg",
    "large": false
  },
  {
    "id": "stainless-1",
    "name": "باب غرف إستيل راقي HM-ST-01",
    "code": "HM-ST-01",
    "category": "استانلس",
    "tags": [
      "خامات فاخرة",
      "مقاوم للخدش",
      "تصميم تركي"
    ],
    "image": "./images/catalog/stainless/stainless-1.jpeg",
    "large": false
  },
  {
    "id": "stainless-2",
    "name": "باب غرف إستيل راقي HM-ST-02",
    "code": "HM-ST-02",
    "category": "استانلس",
    "tags": [
      "خامات فاخرة",
      "مقاوم للخدش",
      "تصميم تركي"
    ],
    "badge": "راقي",
    "image": "./images/catalog/stainless/stainless-2.jpeg",
    "large": false
  },
  {
    "id": "stainless-3",
    "name": "باب غرف إستيل راقي HM-ST-03",
    "code": "HM-ST-03",
    "category": "استانلس",
    "tags": [
      "مقاوم للخدش",
      "شريط إستيل ذهبي",
      "مقاوم للصدأ"
    ],
    "image": "./images/catalog/stainless/stainless-3.jpeg",
    "large": false
  },
  {
    "id": "stainless-4",
    "name": "باب غرف إستيل راقي HM-ST-04",
    "code": "HM-ST-04",
    "category": "استانلس",
    "tags": [
      "خامات فاخرة",
      "مقاوم للصدأ",
      "تصميم تركي"
    ],
    "image": "./images/catalog/stainless/stainless-4.jpeg",
    "large": false
  },
  {
    "id": "stainless-5",
    "name": "باب غرف إستيل راقي HM-ST-05",
    "code": "HM-ST-05",
    "category": "استانلس",
    "tags": [
      "مقاوم للخدش",
      "تصميم تركي",
      "مقاوم للصدأ"
    ],
    "image": "./images/catalog/stainless/stainless-5.jpeg",
    "large": false
  },
  {
    "id": "stainless-6",
    "name": "باب غرف إستيل راقي HM-ST-06",
    "code": "HM-ST-06",
    "category": "استانلس",
    "tags": [
      "تصميم تركي",
      "خامات فاخرة",
      "مقاوم للصدأ"
    ],
    "image": "./images/catalog/stainless/stainless-6.jpeg",
    "large": false
  },
  {
    "id": "stainless-7",
    "name": "باب غرف إستيل راقي HM-ST-07",
    "code": "HM-ST-07",
    "category": "استانلس",
    "tags": [
      "شريط إستيل ذهبي",
      "مقاوم للخدش",
      "مقاوم للصدأ"
    ],
    "image": "./images/catalog/stainless/stainless-7.jpeg",
    "large": false
  },
  {
    "id": "stainless-8",
    "name": "باب غرف إستيل راقي HM-ST-08",
    "code": "HM-ST-08",
    "category": "استانلس",
    "tags": [
      "خامات فاخرة",
      "مقاوم للصدأ",
      "شريط إستيل ذهبي"
    ],
    "image": "./images/catalog/stainless/stainless-8.jpeg",
    "large": false
  },
  {
    "id": "stainless-9",
    "name": "باب غرف إستيل راقي HM-ST-09",
    "code": "HM-ST-09",
    "category": "استانلس",
    "tags": [
      "شريط إستيل ذهبي",
      "مقاوم للصدأ",
      "تصميم تركي"
    ],
    "badge": "راقي",
    "image": "./images/catalog/stainless/stainless-9.jpeg",
    "large": false
  },
  {
    "id": "stainless-10",
    "name": "باب غرف إستيل راقي HM-ST-10",
    "code": "HM-ST-10",
    "category": "استانلس",
    "tags": [
      "مقاوم للصدأ",
      "شريط إستيل ذهبي",
      "تصميم تركي"
    ],
    "image": "./images/catalog/stainless/stainless-10.jpeg",
    "large": false
  },
  {
    "id": "stainless-11",
    "name": "باب غرف إستيل راقي HM-ST-11",
    "code": "HM-ST-11",
    "category": "استانلس",
    "tags": [
      "خامات فاخرة",
      "مقاوم للخدش",
      "تصميم تركي"
    ],
    "image": "./images/catalog/stainless/stainless-11.jpeg",
    "large": false
  },
  {
    "id": "stainless-12",
    "name": "باب غرف إستيل راقي HM-ST-12",
    "code": "HM-ST-12",
    "category": "استانلس",
    "tags": [
      "تصميم تركي",
      "مقاوم للخدش",
      "خامات فاخرة"
    ],
    "image": "./images/catalog/stainless/stainless-12.jpeg",
    "large": false
  },
  {
    "id": "stainless-13",
    "name": "باب غرف إستيل راقي HM-ST-13",
    "code": "HM-ST-13",
    "category": "استانلس",
    "tags": [
      "خامات فاخرة",
      "مقاوم للخدش",
      "تصميم تركي"
    ],
    "image": "./images/catalog/stainless/stainless-13.jpeg",
    "large": false
  },
  {
    "id": "stainless-14",
    "name": "باب غرف إستيل راقي HM-ST-14",
    "code": "HM-ST-14",
    "category": "استانلس",
    "tags": [
      "مقاوم للصدأ",
      "تصميم تركي",
      "شريط إستيل ذهبي"
    ],
    "image": "./images/catalog/stainless/stainless-14.jpeg",
    "large": false
  },
  {
    "id": "stainless-15",
    "name": "باب غرف إستيل راقي HM-ST-15",
    "code": "HM-ST-15",
    "category": "استانلس",
    "tags": [
      "شريط إستيل ذهبي",
      "مقاوم للصدأ",
      "تصميم تركي"
    ],
    "image": "./images/catalog/stainless/stainless-15.jpeg",
    "large": false
  },
  {
    "id": "stainless-16",
    "name": "باب غرف إستيل راقي HM-ST-16",
    "code": "HM-ST-16",
    "category": "استانلس",
    "tags": [
      "شريط إستيل ذهبي",
      "مقاوم للصدأ",
      "تصميم تركي"
    ],
    "image": "./images/catalog/stainless/stainless-16.jpeg",
    "large": false
  },
  {
    "id": "stainless-17",
    "name": "باب غرف إستيل راقي HM-ST-17",
    "code": "HM-ST-17",
    "category": "استانلس",
    "tags": [
      "شريط إستيل ذهبي",
      "مقاوم للصدأ",
      "مقاوم للخدش"
    ],
    "badge": "الأكثر مبيعاً",
    "image": "./images/catalog/stainless/stainless-17.jpeg",
    "large": false
  },
  {
    "id": "stainless-18",
    "name": "باب غرف إستيل راقي HM-ST-18",
    "code": "HM-ST-18",
    "category": "استانلس",
    "tags": [
      "شريط إستيل ذهبي",
      "مقاوم للصدأ",
      "تصميم تركي"
    ],
    "image": "./images/catalog/stainless/stainless-18.jpeg",
    "large": false
  },
  {
    "id": "stainless-19",
    "name": "باب غرف إستيل راقي HM-ST-19",
    "code": "HM-ST-19",
    "category": "استانلس",
    "tags": [
      "شريط إستيل ذهبي",
      "مقاوم للصدأ",
      "خامات فاخرة"
    ],
    "image": "./images/catalog/stainless/stainless-19.jpeg",
    "large": false
  },
  {
    "id": "stainless-20",
    "name": "باب غرف إستيل راقي HM-ST-20",
    "code": "HM-ST-20",
    "category": "استانلس",
    "tags": [
      "شريط إستيل ذهبي",
      "تصميم تركي",
      "مقاوم للصدأ"
    ],
    "image": "./images/catalog/stainless/stainless-20.jpeg",
    "large": false
  },
  {
    "id": "stainless-21",
    "name": "باب غرف إستيل راقي HM-ST-21",
    "code": "HM-ST-21",
    "category": "استانلس",
    "tags": [
      "شريط إستيل ذهبي",
      "مقاوم للصدأ",
      "مقاوم للخدش"
    ],
    "image": "./images/catalog/stainless/stainless-21.jpeg",
    "large": false
  },
  {
    "id": "stainless-22",
    "name": "باب غرف إستيل راقي HM-ST-22",
    "code": "HM-ST-22",
    "category": "استانلس",
    "tags": [
      "خامات فاخرة",
      "مقاوم للخدش",
      "تصميم تركي"
    ],
    "image": "./images/catalog/stainless/stainless-22.jpeg",
    "large": false
  },
  {
    "id": "stainless-23",
    "name": "باب غرف إستيل راقي HM-ST-23",
    "code": "HM-ST-23",
    "category": "استانلس",
    "tags": [
      "مقاوم للخدش",
      "تصميم تركي",
      "خامات فاخرة"
    ],
    "image": "./images/catalog/stainless/stainless-23.jpeg",
    "large": false
  },
  {
    "id": "stainless-24",
    "name": "باب غرف إستيل راقي HM-ST-24",
    "code": "HM-ST-24",
    "category": "استانلس",
    "tags": [
      "شريط إستيل ذهبي",
      "مقاوم للصدأ",
      "خامات فاخرة"
    ],
    "image": "./images/catalog/stainless/stainless-24.jpeg",
    "large": false
  },
  {
    "id": "hafr-1",
    "name": "باب غرف حفر سي إن سي HM-HF-01",
    "code": "HM-HF-01",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "قشرة طبيعية",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-1.jpeg",
    "large": false
  },
  {
    "id": "hafr-2",
    "name": "باب غرف حفر سي إن سي HM-HF-02",
    "code": "HM-HF-02",
    "category": "حفر",
    "tags": [
      "دهان بولي يوريثان",
      "قشرة طبيعية",
      "CNC حفر كمبيوتر"
    ],
    "image": "./images/catalog/hafr/hafr-2.jpeg",
    "large": false
  },
  {
    "id": "hafr-3",
    "name": "باب غرف حفر سي إن سي HM-HF-03",
    "code": "HM-HF-03",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "دهان بولي يوريثان",
      "متانة عالية"
    ],
    "image": "./images/catalog/hafr/hafr-3.jpeg",
    "large": false
  },
  {
    "id": "hafr-4",
    "name": "باب غرف حفر سي إن سي HM-HF-04",
    "code": "HM-HF-04",
    "category": "حفر",
    "tags": [
      "دهان بولي يوريثان",
      "CNC حفر كمبيوتر",
      "كلاسيك راقي"
    ],
    "image": "./images/catalog/hafr/hafr-4.jpeg",
    "large": false
  },
  {
    "id": "hafr-5",
    "name": "باب غرف حفر سي إن سي HM-HF-05",
    "code": "HM-HF-05",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "كلاسيك راقي",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-5.jpeg",
    "large": false
  },
  {
    "id": "hafr-6",
    "name": "باب غرف حفر سي إن سي HM-HF-06",
    "code": "HM-HF-06",
    "category": "حفر",
    "tags": [
      "كلاسيك راقي",
      "متانة عالية",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-6.jpeg",
    "large": false
  },
  {
    "id": "hafr-7",
    "name": "باب غرف حفر سي إن سي HM-HF-07",
    "code": "HM-HF-07",
    "category": "حفر",
    "tags": [
      "كلاسيك راقي",
      "دهان بولي يوريثان",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-7.jpeg",
    "large": false
  },
  {
    "id": "hafr-8",
    "name": "باب غرف حفر سي إن سي HM-HF-08",
    "code": "HM-HF-08",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "كلاسيك راقي",
      "دهان بولي يوريثان"
    ],
    "badge": "راقي",
    "image": "./images/catalog/hafr/hafr-8.jpeg",
    "large": false
  },
  {
    "id": "hafr-9",
    "name": "باب غرف حفر سي إن سي HM-HF-09",
    "code": "HM-HF-09",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "دهان بولي يوريثان",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-9.jpeg",
    "large": false
  },
  {
    "id": "hafr-10",
    "name": "باب غرف حفر سي إن سي HM-HF-10",
    "code": "HM-HF-10",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "قشرة طبيعية",
      "متانة عالية"
    ],
    "image": "./images/catalog/hafr/hafr-10.jpeg",
    "large": false
  },
  {
    "id": "hafr-11",
    "name": "باب غرف حفر سي إن سي HM-HF-11",
    "code": "HM-HF-11",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "قشرة طبيعية",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-11.jpeg",
    "large": false
  },
  {
    "id": "hafr-12",
    "name": "باب غرف حفر سي إن سي HM-HF-12",
    "code": "HM-HF-12",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "متانة عالية",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-12.jpeg",
    "large": false
  },
  {
    "id": "hafr-13",
    "name": "باب غرف حفر سي إن سي HM-HF-13",
    "code": "HM-HF-13",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "دهان بولي يوريثان",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-13.jpeg",
    "large": false
  },
  {
    "id": "hafr-14",
    "name": "باب غرف حفر سي إن سي HM-HF-14",
    "code": "HM-HF-14",
    "category": "حفر",
    "tags": [
      "كلاسيك راقي",
      "قشرة طبيعية",
      "CNC حفر كمبيوتر"
    ],
    "image": "./images/catalog/hafr/hafr-14.jpeg",
    "large": false
  },
  {
    "id": "hafr-15",
    "name": "باب غرف حفر سي إن سي HM-HF-15",
    "code": "HM-HF-15",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "CNC حفر كمبيوتر",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-15.jpeg",
    "large": false
  },
  {
    "id": "hafr-16",
    "name": "باب غرف حفر سي إن سي HM-HF-16",
    "code": "HM-HF-16",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "قشرة طبيعية",
      "دهان بولي يوريثان"
    ],
    "badge": "جديد",
    "image": "./images/catalog/hafr/hafr-16.jpeg",
    "large": false
  },
  {
    "id": "hafr-17",
    "name": "باب غرف حفر سي إن سي HM-HF-17",
    "code": "HM-HF-17",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "CNC حفر كمبيوتر",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-17.jpeg",
    "large": false
  },
  {
    "id": "hafr-18",
    "name": "باب غرف حفر سي إن سي HM-HF-18",
    "code": "HM-HF-18",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "دهان بولي يوريثان",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-18.jpeg",
    "large": false
  },
  {
    "id": "hafr-19",
    "name": "باب غرف حفر سي إن سي HM-HF-19",
    "code": "HM-HF-19",
    "category": "حفر",
    "tags": [
      "كلاسيك راقي",
      "دهان بولي يوريثان",
      "متانة عالية"
    ],
    "image": "./images/catalog/hafr/hafr-19.jpeg",
    "large": false
  },
  {
    "id": "hafr-20",
    "name": "باب غرف حفر سي إن سي HM-HF-20",
    "code": "HM-HF-20",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "كلاسيك راقي",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-20.jpeg",
    "large": false
  },
  {
    "id": "hafr-21",
    "name": "باب غرف حفر سي إن سي HM-HF-21",
    "code": "HM-HF-21",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "قشرة طبيعية",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-21.jpeg",
    "large": false
  },
  {
    "id": "hafr-22",
    "name": "باب غرف حفر سي إن سي HM-HF-22",
    "code": "HM-HF-22",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "CNC حفر كمبيوتر",
      "كلاسيك راقي"
    ],
    "image": "./images/catalog/hafr/hafr-22.jpeg",
    "large": false
  },
  {
    "id": "hafr-23",
    "name": "باب غرف حفر سي إن سي HM-HF-23",
    "code": "HM-HF-23",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "قشرة طبيعية",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-23.jpeg",
    "large": false
  },
  {
    "id": "hafr-24",
    "name": "باب غرف حفر سي إن سي HM-HF-24",
    "code": "HM-HF-24",
    "category": "حفر",
    "tags": [
      "كلاسيك راقي",
      "CNC حفر كمبيوتر",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-24.jpeg",
    "large": false
  },
  {
    "id": "hafr-25",
    "name": "باب غرف حفر سي إن سي HM-HF-25",
    "code": "HM-HF-25",
    "category": "حفر",
    "tags": [
      "قشرة طبيعية",
      "CNC حفر كمبيوتر",
      "كلاسيك راقي"
    ],
    "image": "./images/catalog/hafr/hafr-25.jpeg",
    "large": false
  },
  {
    "id": "hafr-26",
    "name": "باب غرف حفر سي إن سي HM-HF-26",
    "code": "HM-HF-26",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "قشرة طبيعية",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-26.jpeg",
    "large": false
  },
  {
    "id": "hafr-27",
    "name": "باب غرف حفر سي إن سي HM-HF-27",
    "code": "HM-HF-27",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "متانة عالية",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-27.jpeg",
    "large": false
  },
  {
    "id": "hafr-28",
    "name": "باب غرف حفر سي إن سي HM-HF-28",
    "code": "HM-HF-28",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "CNC حفر كمبيوتر",
      "كلاسيك راقي"
    ],
    "image": "./images/catalog/hafr/hafr-28.jpeg",
    "large": false
  },
  {
    "id": "hafr-29",
    "name": "باب غرف حفر سي إن سي HM-HF-29",
    "code": "HM-HF-29",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "كلاسيك راقي",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-29.jpeg",
    "large": false
  },
  {
    "id": "hafr-30",
    "name": "باب غرف حفر سي إن سي HM-HF-30",
    "code": "HM-HF-30",
    "category": "حفر",
    "tags": [
      "كلاسيك راقي",
      "دهان بولي يوريثان",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-30.jpeg",
    "large": false
  },
  {
    "id": "hafr-31",
    "name": "باب غرف حفر سي إن سي HM-HF-31",
    "code": "HM-HF-31",
    "category": "حفر",
    "tags": [
      "قشرة طبيعية",
      "كلاسيك راقي",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-31.jpeg",
    "large": false
  },
  {
    "id": "hafr-32",
    "name": "باب غرف حفر سي إن سي HM-HF-32",
    "code": "HM-HF-32",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "قشرة طبيعية",
      "كلاسيك راقي"
    ],
    "image": "./images/catalog/hafr/hafr-32.jpeg",
    "large": false
  },
  {
    "id": "hafr-33",
    "name": "باب غرف حفر سي إن سي HM-HF-33",
    "code": "HM-HF-33",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "كلاسيك راقي",
      "متانة عالية"
    ],
    "image": "./images/catalog/hafr/hafr-33.jpeg",
    "large": false
  },
  {
    "id": "hafr-34",
    "name": "باب غرف حفر سي إن سي HM-HF-34",
    "code": "HM-HF-34",
    "category": "حفر",
    "tags": [
      "قشرة طبيعية",
      "كلاسيك راقي",
      "متانة عالية"
    ],
    "image": "./images/catalog/hafr/hafr-34.jpeg",
    "large": false
  },
  {
    "id": "hafr-35",
    "name": "باب غرف حفر سي إن سي HM-HF-35",
    "code": "HM-HF-35",
    "category": "حفر",
    "tags": [
      "كلاسيك راقي",
      "دهان بولي يوريثان",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-35.jpeg",
    "large": false
  },
  {
    "id": "hafr-36",
    "name": "باب غرف حفر سي إن سي HM-HF-36",
    "code": "HM-HF-36",
    "category": "حفر",
    "tags": [
      "قشرة طبيعية",
      "كلاسيك راقي",
      "متانة عالية"
    ],
    "badge": "الأكثر مبيعاً",
    "image": "./images/catalog/hafr/hafr-36.jpeg",
    "large": false
  },
  {
    "id": "hafr-37",
    "name": "باب غرف حفر سي إن سي HM-HF-37",
    "code": "HM-HF-37",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "قشرة طبيعية",
      "كلاسيك راقي"
    ],
    "image": "./images/catalog/hafr/hafr-37.jpeg",
    "large": false
  },
  {
    "id": "hafr-38",
    "name": "باب غرف حفر سي إن سي HM-HF-38",
    "code": "HM-HF-38",
    "category": "حفر",
    "tags": [
      "متانة عالية",
      "كلاسيك راقي",
      "دهان بولي يوريثان"
    ],
    "image": "./images/catalog/hafr/hafr-38.jpeg",
    "large": false
  },
  {
    "id": "hafr-39",
    "name": "باب غرف حفر سي إن سي HM-HF-39",
    "code": "HM-HF-39",
    "category": "حفر",
    "tags": [
      "CNC حفر كمبيوتر",
      "متانة عالية",
      "قشرة طبيعية"
    ],
    "image": "./images/catalog/hafr/hafr-39.jpeg",
    "large": false
  },
  {
    "id": "hafr-40",
    "name": "باب غرف حفر سي إن سي HM-HF-40",
    "code": "HM-HF-40",
    "category": "حفر",
    "tags": [
      "كلاسيك راقي",
      "قشرة طبيعية",
      "متانة عالية"
    ],
    "image": "./images/catalog/hafr/hafr-40.jpeg",
    "large": false
  },
  {
    "id": "acrylic-1",
    "name": "باب بارز أكريليك فاخر HM-AC-01",
    "code": "HM-AC-01",
    "category": "بارز",
    "tags": [
      "لمعان فائق",
      "أكريليك بارز",
      "مقاوم للمياه"
    ],
    "image": "./images/catalog/acrylic/acrylic-1.jpeg",
    "large": true
  },
  {
    "id": "acrylic-2",
    "name": "باب بارز أكريليك فاخر HM-AC-02",
    "code": "HM-AC-02",
    "category": "بارز",
    "tags": [
      "أكريليك بارز",
      "تصميم متداخل",
      "لمعان فائق"
    ],
    "image": "./images/catalog/acrylic/acrylic-2.jpeg",
    "large": false
  },
  {
    "id": "acrylic-3",
    "name": "باب بارز أكريليك فاخر HM-AC-03",
    "code": "HM-AC-03",
    "category": "بارز",
    "tags": [
      "أكريليك بارز",
      "تصميم متداخل",
      "لمعان فائق"
    ],
    "image": "./images/catalog/acrylic/acrylic-3.jpeg",
    "large": false
  },
  {
    "id": "acrylic-4",
    "name": "باب بارز أكريليك فاخر HM-AC-04",
    "code": "HM-AC-04",
    "category": "بارز",
    "tags": [
      "أكريليك بارز",
      "تصميم متداخل",
      "مقاوم للبكتيريا"
    ],
    "image": "./images/catalog/acrylic/acrylic-4.jpeg",
    "large": false
  },
  {
    "id": "acrylic-5",
    "name": "باب بارز أكريليك فاخر HM-AC-05",
    "code": "HM-AC-05",
    "category": "بارز",
    "tags": [
      "تصميم متداخل",
      "لمعان فائق",
      "مقاوم للمياه"
    ],
    "image": "./images/catalog/acrylic/acrylic-5.jpeg",
    "large": false
  },
  {
    "id": "acrylic-6",
    "name": "باب بارز أكريليك فاخر HM-AC-06",
    "code": "HM-AC-06",
    "category": "بارز",
    "tags": [
      "أكريليك بارز",
      "لمعان فائق",
      "مقاوم للمياه"
    ],
    "image": "./images/catalog/acrylic/acrylic-6.jpeg",
    "large": false
  },
  {
    "id": "acrylic-7",
    "name": "باب بارز أكريليك فاخر HM-AC-07",
    "code": "HM-AC-07",
    "category": "بارز",
    "tags": [
      "مقاوم للبكتيريا",
      "أكريليك بارز",
      "تصميم متداخل"
    ],
    "image": "./images/catalog/acrylic/acrylic-7.jpeg",
    "large": false
  },
  {
    "id": "acrylic-8",
    "name": "باب بارز أكريليك فاخر HM-AC-08",
    "code": "HM-AC-08",
    "category": "بارز",
    "tags": [
      "أكريليك بارز",
      "مقاوم للبكتيريا",
      "تصميم متداخل"
    ],
    "image": "./images/catalog/acrylic/acrylic-8.jpeg",
    "large": false
  },
  {
    "id": "acrylic-9",
    "name": "باب بارز أكريليك فاخر HM-AC-09",
    "code": "HM-AC-09",
    "category": "بارز",
    "tags": [
      "مقاوم للبكتيريا",
      "لمعان فائق",
      "تصميم متداخل"
    ],
    "image": "./images/catalog/acrylic/acrylic-9.jpeg",
    "large": false
  },
  {
    "id": "acrylic-10",
    "name": "باب بارز أكريليك فاخر HM-AC-10",
    "code": "HM-AC-10",
    "category": "بارز",
    "tags": [
      "مقاوم للبكتيريا",
      "مقاوم للمياه",
      "تصميم متداخل"
    ],
    "image": "./images/catalog/acrylic/acrylic-10.jpeg",
    "large": false
  },
  {
    "id": "acrylic-11",
    "name": "باب بارز أكريليك فاخر HM-AC-11",
    "code": "HM-AC-11",
    "category": "بارز",
    "tags": [
      "تصميم متداخل",
      "مقاوم للبكتيريا",
      "لمعان فائق"
    ],
    "badge": "راقي",
    "image": "./images/catalog/acrylic/acrylic-11.jpeg",
    "large": false
  },
  {
    "id": "acrylic-12",
    "name": "باب بارز أكريليك فاخر HM-AC-12",
    "code": "HM-AC-12",
    "category": "بارز",
    "tags": [
      "مقاوم للبكتيريا",
      "لمعان فائق",
      "مقاوم للمياه"
    ],
    "badge": "جديد",
    "image": "./images/catalog/acrylic/acrylic-12.jpeg",
    "large": false
  },
  {
    "id": "acrylic-13",
    "name": "باب بارز أكريليك فاخر HM-AC-13",
    "code": "HM-AC-13",
    "category": "بارز",
    "tags": [
      "تصميم متداخل",
      "أكريليك بارز",
      "لمعان فائق"
    ],
    "image": "./images/catalog/acrylic/acrylic-13.jpeg",
    "large": false
  },
  {
    "id": "acrylic-14",
    "name": "باب بارز أكريليك فاخر HM-AC-14",
    "code": "HM-AC-14",
    "category": "بارز",
    "tags": [
      "تصميم متداخل",
      "أكريليك بارز",
      "لمعان فائق"
    ],
    "image": "./images/catalog/acrylic/acrylic-14.jpeg",
    "large": false
  },
  {
    "id": "acrylic-15",
    "name": "باب بارز أكريليك فاخر HM-AC-15",
    "code": "HM-AC-15",
    "category": "بارز",
    "tags": [
      "أكريليك بارز",
      "لمعان فائق",
      "مقاوم للمياه"
    ],
    "image": "./images/catalog/acrylic/acrylic-15.jpeg",
    "large": false
  },
  {
    "id": "acrylic-16",
    "name": "باب بارز أكريليك فاخر HM-AC-16",
    "code": "HM-AC-16",
    "category": "بارز",
    "tags": [
      "مقاوم للبكتيريا",
      "لمعان فائق",
      "تصميم متداخل"
    ],
    "image": "./images/catalog/acrylic/acrylic-16.jpeg",
    "large": false
  },
  {
    "id": "acrylic-17",
    "name": "باب بارز أكريليك فاخر HM-AC-17",
    "code": "HM-AC-17",
    "category": "بارز",
    "tags": [
      "أكريليك بارز",
      "تصميم متداخل",
      "لمعان فائق"
    ],
    "image": "./images/catalog/acrylic/acrylic-17.jpeg",
    "large": false
  },
  {
    "id": "acrylic-18",
    "name": "باب بارز أكريليك فاخر HM-AC-18",
    "code": "HM-AC-18",
    "category": "بارز",
    "tags": [
      "تصميم متداخل",
      "أكريليك بارز",
      "مقاوم للبكتيريا"
    ],
    "badge": "طلب خاص",
    "image": "./images/catalog/acrylic/acrylic-18.jpeg",
    "large": false
  },
  {
    "id": "acrylic-19",
    "name": "باب بارز أكريليك فاخر HM-AC-19",
    "code": "HM-AC-19",
    "category": "بارز",
    "tags": [
      "تصميم متداخل",
      "مقاوم للبكتيريا",
      "مقاوم للمياه"
    ],
    "image": "./images/catalog/acrylic/acrylic-19.jpeg",
    "large": false
  },
  {
    "id": "acrylic-20",
    "name": "باب بارز أكريليك فاخر HM-AC-20",
    "code": "HM-AC-20",
    "category": "بارز",
    "tags": [
      "مقاوم للبكتيريا",
      "لمعان فائق",
      "تصميم متداخل"
    ],
    "badge": "راقي",
    "image": "./images/catalog/acrylic/acrylic-20.jpeg",
    "large": false
  },
  {
    "id": "acrylic-21",
    "name": "باب بارز أكريليك فاخر HM-AC-21",
    "code": "HM-AC-21",
    "category": "بارز",
    "tags": [
      "مقاوم للمياه",
      "مقاوم للبكتيريا",
      "تصميم متداخل"
    ],
    "image": "./images/catalog/acrylic/acrylic-21.jpeg",
    "large": false
  },
  {
    "id": "acrylic-22",
    "name": "باب بارز أكريليك فاخر HM-AC-22",
    "code": "HM-AC-22",
    "category": "بارز",
    "tags": [
      "مقاوم للمياه",
      "مقاوم للبكتيريا",
      "لمعان فائق"
    ],
    "image": "./images/catalog/acrylic/acrylic-22.jpeg",
    "large": false
  },
  {
    "id": "acrylic-23",
    "name": "باب بارز أكريليك فاخر HM-AC-23",
    "code": "HM-AC-23",
    "category": "بارز",
    "tags": [
      "مقاوم للبكتيريا",
      "مقاوم للمياه",
      "أكريليك بارز"
    ],
    "image": "./images/catalog/acrylic/acrylic-23.jpeg",
    "large": false
  },
  {
    "id": "acrylic-24",
    "name": "باب بارز أكريليك فاخر HM-AC-24",
    "code": "HM-AC-24",
    "category": "بارز",
    "tags": [
      "مقاوم للمياه",
      "لمعان فائق",
      "تصميم متداخل"
    ],
    "image": "./images/catalog/acrylic/acrylic-24.jpeg",
    "large": false
  },
  {
    "id": "acrylic-25",
    "name": "باب بارز أكريليك فاخر HM-AC-25",
    "code": "HM-AC-25",
    "category": "بارز",
    "tags": [
      "مقاوم للمياه",
      "تصميم متداخل",
      "مقاوم للبكتيريا"
    ],
    "image": "./images/catalog/acrylic/acrylic-25.jpeg",
    "large": false
  },
  {
    "id": "acrylic-26",
    "name": "باب بارز أكريليك فاخر HM-AC-26",
    "code": "HM-AC-26",
    "category": "بارز",
    "tags": [
      "أكريليك بارز",
      "تصميم متداخل",
      "مقاوم للبكتيريا"
    ],
    "badge": "تصميم مميز",
    "image": "./images/catalog/acrylic/acrylic-26.jpeg",
    "large": false
  },
  {
    "id": "acrylic-27",
    "name": "باب بارز أكريليك فاخر HM-AC-27",
    "code": "HM-AC-27",
    "category": "بارز",
    "tags": [
      "مقاوم للبكتيريا",
      "لمعان فائق",
      "تصميم متداخل"
    ],
    "image": "./images/catalog/acrylic/acrylic-27.jpeg",
    "large": false
  },
  {
    "id": "acrylic-28",
    "name": "باب بارز أكريليك فاخر HM-AC-28",
    "code": "HM-AC-28",
    "category": "بارز",
    "tags": [
      "أكريليك بارز",
      "تصميم متداخل",
      "لمعان فائق"
    ],
    "image": "./images/catalog/acrylic/acrylic-28.jpeg",
    "large": false
  },
  {
    "id": "windows-1",
    "name": "شباك ألومنيوم مودرن HM-WN-01",
    "code": "HM-WN-01",
    "category": "شبابيك",
    "tags": [
      "مانع للأتربة",
      "إكسسوارات إيطالية",
      "عازل للصوت"
    ],
    "image": "./images/catalog/windows/windows-1.jpeg",
    "large": false
  },
  {
    "id": "windows-2",
    "name": "شباك ألومنيوم مودرن HM-WN-02",
    "code": "HM-WN-02",
    "category": "شبابيك",
    "tags": [
      "قطاع عريض",
      "مانع للأتربة",
      "عازل للصوت"
    ],
    "image": "./images/catalog/windows/windows-2.jpeg",
    "large": false
  },
  {
    "id": "windows-3",
    "name": "شباك ألومنيوم مودرن HM-WN-03",
    "code": "HM-WN-03",
    "category": "شبابيك",
    "tags": [
      "قطاع عريض",
      "زجاج دبل عازل",
      "إكسسوارات إيطالية"
    ],
    "image": "./images/catalog/windows/windows-3.jpeg",
    "large": false
  },
  {
    "id": "windows-4",
    "name": "شباك ألومنيوم مودرن HM-WN-04",
    "code": "HM-WN-04",
    "category": "شبابيك",
    "tags": [
      "عازل للصوت",
      "مانع للأتربة",
      "إكسسوارات إيطالية"
    ],
    "image": "./images/catalog/windows/windows-4.jpeg",
    "large": false
  }
];
